### ISSUE TITLE
Stop moving when next to food

### ISSUE THREAD

**Issue by benjalon** [benjalon/evolution-sim#85]
There seems to be a bug where if you spawn loads of food in they will eventually stop moving in a cluster. 
![image](https://user-images.githubusercontent.com/14875816/48380205-c9514c80-e6ce-11e8-995c-2787345c3008.png)

Dunno if this is to do with hunger. 

Once another organism comes and eats the food they start moving again.

**Comment by benjalon** [comment]
And i've left them for a while, its not that they're just randomly picking inhabited tiles in roam

**Comment by RyanJP18** [comment]
This is likely related to the pathfinding not ignoring occupied tiles. Newer ticket: https://github.com/benjalon/evolution-sim/issues/120
